### ISSUE TITLE
getting errors while downloading podcasts

### ISSUE THREAD

**Issue by bajechele** [lightpohl/podcast-dl#24]
so i was downloading a podcast with 100 episodes but i got error after downloading 21 of them
this was the error 

22 of 100
(node:10364) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at validateString (internal/validators.js:121:11)
    at Object.extname (path.js:752:5)
    at getUrlExt (C:\snapshot\podcast-dl\bin\util.js:160:20)
    at getIsAudioUrl (C:\snapshot\podcast-dl\bin\util.js:179:15)
    at getEpisodeAudioUrlAndExt (C:\snapshot\podcast-dl\bin\util.js:188:20)
    at main (C:\snapshot\podcast-dl\bin\bin.js:234:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `podcast-dl --trace-warnings ...` to show where the warning was created)
(node:10364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

can u plzz help in fixing this  and [this was the link i was trying to download](https://audioboom.com/channels/5012360.rss)

**Comment by lightpohl** [comment]
Hey @bajechele!

It looks like the feed entry for that episode is invalid. It's missing both the enclosure data and the link URL doesn't have an extension on it.

```sh
{ length: '', type: 'audio/mpeg', url: '' }

https://mahabharat.simplecast.com/episodes/79-bheem-kills-keechak-bhiim-dvaaraa-kiick-kaa-ant-uTc4cX14
```

I can prevent this from erroring during the run in a patch, but the script can't download this episode. To skip that episode and download the rest you can provide an `--offset 22`. Then you can download that invalid episode manually.

**Comment by lightpohl** [comment]
Just released [v4.3.1](https://github.com/lightpohl/podcast-dl/releases/tag/v4.3.1) which will skip over these episodes when it finds them—so you won't need to use the `--offset` trick mentioned above to skip them. 👍

**Comment by bajechele** [comment]
thanks a ton now it is working fine .......with this update from the above rss link it managed to download 95 of them which is way better than stop at the middle at 22nd download .....did u tried that link and except no 22 did u managed to get all of them ?

**Comment by lightpohl** [comment]
@bajechele - Hey! No, there are a few invalid episodes in their RSS feed. You would need to contact the owner of the feed to have them fix the list or download those few episodes manually.

**Comment by bajechele** [comment]
i downed those 5 normally but this tool helped a lot 95 automated download  thanks a ton for this tool..... 
can i ask if this is possible like imagine i have a list like 5 to 10 podcast that i listen like my fav so is there a way like i can save those link to a txt file and feed that txt file to this podcast-dl and use ""podcast-dl --limit 1 -f feedlist.txt"  and it will downloads all the latest episodes from all those 10 or 15 rss feed urls.

**Comment by lightpohl** [comment]
I don't have plans at the moment to support multiple feeds in this script. But you can definitely wrap calling the script however you like! It requires learning some basic shell or JavaScript though.

**Comment by bajechele** [comment]
i know nothing about those shell and jscript :(  but will wait for u when ever u add .....after all this will b a good feature for this tool
