### ISSUE TITLE
A 0-byte archive file crashes podcast-dl

### ISSUE THREAD

**Issue by Simon818** [lightpohl/podcast-dl#49]
If you try to point podcast-dl at an archive file that exists and is empty, you get a lot of JSON errors:

> Downloading podcast image...  
Unable to download podcast image  
Unexpected end of JSON input  
Saving podcast metadata...  
Unable to save podcast metadata  
Unexpected end of JSON input  
undefined:1  
SyntaxError: Unexpected end of JSON input  
    at JSON.parse (<anonymous>)  
    at getJsonFile (file:///usr/lib/node_modules/podcast-dl/bin/util.js:39:15)  
    at getArchive (file:///usr/lib/node_modules/podcast-dl/bin/util.js:43:26)  
    at getItemsToDownload (file:///usr/lib/node_modules/podcast-dl/bin/util.js:112:34)  
    at main (file:///usr/lib/node_modules/podcast-dl/bin/bin.js:172:23)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
Node.js v19.9.0

This is highly avoidable on my end, I just thought it was worth mentioning.

**Comment by lightpohl** [comment]
Hey! Thanks for the report!

We can definitely handle that more gracefully. 👍

**Comment by lightpohl** [comment]
Thanks again! This will be fixed when I publish v8.0.8 next week. 🚀
